version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      - bundle_cache:/bundle
      - sqlite-data:/workspace/data

    ports:
      - '3000:3000'

    command: sleep infinity

    environment:
      REDIS_URL: redis://redis:6379/1
      TZ: America/New_York
      RUBYOPT: "--yjit"

    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mailgun:
    image: marlonb/mailcrab:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  sqlite-data:
  bundle_cache:
