apps:
  - name: "Basecamp"
    app_category: "Project Management"
    ios_url: "https://apps.apple.com/us/app/basecamp-project-management/id1015603248"
    android_url: "https://play.google.com/store/apps/details?id=com.basecamp.bc3&hl=en_US&gl=US&pli=1"
    web_url: "https://basecamp.com"
    image: "basecamp.webp"

  - name: "HEY Email"
    app_category: "Email"
    ios_url: "https://apps.apple.com/us/app/hey-email/id1506603805"
    android_url: "https://play.google.com/store/apps/details?id=com.basecamp.hey"
    web_url: "https://www.hey.com"
    image: "hey_email.webp"

  - name: "HEY Calendar"
    app_category: "Calendar"
    ios_url: "https://apps.apple.com/us/app/hey-calendar/id6449716061"
    android_url: "https://play.google.com/store/apps/details?id=com.basecamp.heycalendar"
    web_url: "https://www.hey.com/calendar"
    image: "hey_calendar.webp"

  - name: "RailsDevs"
    app_category: "Developer Tools"
    ios_url: "https://apps.apple.com/us/app/railsdevs/id1621607837"
    web_url: "https://railsdevs.com"
    image: "railsdevs.webp"

  - name: "Context Travel"
    app_category: "Travel"
    ios_url: "https://apps.apple.com/ca/app/context-travel/id1630419856"
    web_url: "https://www.contexttravel.com"
    image: "context_travel.webp"

  - name: "BeerMenus"
    app_category: "Food & Drink"
    ios_url: "https://apps.apple.com/app/apple-store/id917882057"
    web_url: "https://www.beermenus.com"
    image: "beermenus.webp"

  - name: "PieHoled"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/us/app/pieholed/id6467455236"
    web_url: "https://pieholedapp.com"
    image: "pieholed.webp"

  - name: "Hauling Buddies"
    app_category: "Business"
    android_url: "https://play.google.com/store/apps/details?id=com.haulingbuddies.android"
    web_url: "https://haulingbuddies.com"
    image: "hauling_buddies.webp"

  - name: "Hoist"
    app_category: "Business"
    ios_url: "https://apps.apple.com/us/app/hoist-up/id1592340401"
    image: "hoist.webp"

  - name: "GolfSheet"
    app_category: "Sports"
    ios_url: "https://apps.apple.com/us/app/golf-leaguer/id1627580628"
    image: "golfsheet.webp"

  - name: "OM App: Partnered Meditation"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/app/apple-store/id1635491251"
    web_url: "https://instituteofom.com"
    image: "om.webp"

  - name: "MxU"
    app_category: "Education"
    ios_url: "https://apps.apple.com/us/app/mxu/id6448795537"
    web_url: "https://getmxu.com"
    image: "mxu.webp"

  - name: "Amba - Health and Wellbeing"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/us/app/amba-health-and-wellbeing/id1565130657"
    web_url: "https://www.amba.co"
    image: "amba.webp"

  - name: "PlanGo - for Instructors"
    app_category: "Business"
    ios_url: "https://apps.apple.com/nl/app/plango-instructeursapp/id1096866451"
    android_url: "https://play.google.com/store/apps/details?id=nl.plango.instructeurs"
    image: "plango_instructors.webp"

  - name: "PlanGo - for Students"
    app_category: "Education"
    ios_url: "https://apps.apple.com/nl/app/plango-leerlingapp/id1140253719"
    android_url: "https://play.google.com/store/apps/details?id=nl.plango.leerlingen"
    image: "plango_students.webp"

  - name: "Robodash"
    app_category: "Developer Tools"
    ios_url: "https://apps.apple.com/us/app/robodash/id1522653081"
    image: "robodash.webp"

  - name: "RockLife"
    app_category: "Education"
    ios_url: "https://apps.apple.com/mx/app/rocklife/id1621826773"
    android_url: "https://play.google.com/store/apps/details?id=com.rocklife.app"
    image: "rocklife.webp"

  - name: "Smart Strength"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/ie/app/smart-strength/id1600256651"
    image: "smartstrength.webp"

  - name: "Heatspring"
    app_category: "Education"
    ios_url: "https://apps.apple.com/us/app/heatspring-online-courses/id6449776941"
    image: "heatspring.webp"

  - name: "Enjoy Kitchen"
    app_category: "Food & Drink"
    ios_url: "https://apps.apple.com/mx/app/enjoy-kitchen/id6443742018"
    android_url: "https://play.google.com/store/apps/details?id=mx.enjoykitchen.shop"
    web_url: "https://enjoykitchen.mx"
    image: "enjoy_kitchen.webp"

  - name: "myRent"
    app_category: "Real Estate"
    ios_url: "https://apps.apple.com/us/app/myrent/id6447619622"
    android_url: "https://play.google.com/store/apps/details?id=nz.co.myrent.myRent"
    web_url: "https://myrent.co.nz"
    image: "myrent.webp"

  - name: "Plant Journal - Ploi"
    app_category: "Lifestyle"
    ios_url: "https://apps.apple.com/app/apple-store/id1624280409?pt=124998291&ct=tnd&mt=8"
    android_url: "https://play.google.com/store/apps/details?id=com.devjah.plants"
    image: "ploi.webp"
    web_url: "https://ploi.me/"

  - name: "PLT4M"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/us/app/plt4m/id1291869726"
    android_url: "https://play.google.com/store/apps/details?id=org.mobile.plt4m&pli=1"
    web_url: "https://plt4m.com/"
    image: "plt4m.webp"

  - name: "Sensor Dashboard"
    app_category: "Tools"
    android_url: "https://play.google.com/store/apps/details?id=sensor.dashboard.com"
    web_url: "https://sensor-dashboard.dev-box.ch/"
    image: "sensor_dashboard.webp"

  - name: "Wavclouds"
    app_category: "Music"
    web_url: "https://www.wavclouds.com/"
    android_url: "https://play.google.com/store/apps/details?id=com.wavclouds.mist"
    ios_url: "https://apps.apple.com/us/app/wavclouds/id6465136889"
    source_url: "https://github.com/orgs/Wavclouds/repositories"
    image: "wavclouds.webp"

  - name: "Cital"
    app_category: "Shopping"
    web_url: "https://www.cital.store"
    android_url: "https://play.google.com/store/apps/details?id=co.cital.android.store"
    ios_url: "https://apps.apple.com/us/app/cital-store/id6447628065"
    image: "cital.webp"

  - name: "Daily Log"
    app_category: "Health & Fitness"
    web_url: "https://dailylog.ing"
    ios_url: "https://apps.apple.com/us/app/daily-log-app/id6473819686"
    source_url: "https://github.com/joemasilotti/daily-log"
    image: "daily_log.webp"

  - name: "StepStreak"
    app_category: "Health & Fitness"
    web_url: "https://stepstreak.xyz"
    ios_url: "https://apps.apple.com/en/app/stepstreak/id6474273893"
    image: "stepstreak.webp"

  - name: "1500cals"
    app_category: "Health & Fitness"
    web_url: "https://1500cals.com"
    ios_url: "https://apps.apple.com/app/1500cals/id6470238113"
    image: "1500cals.webp"

  - name: "Swiss Equestrian"
    app_category: "Sports"
    web_url: "https://www.swiss-equestrian.ch/de/Sport/An-Turnieren-teilnehmen/Mobile-App/Mobile-App.html"
    android_url: "https://play.google.com/store/apps/details?id=ch.oxon.myfnch"
    ios_url: "https://apps.apple.com/us/app/swiss-equestrian/id1032326251"
    image: "swiss_equestrian.webp"

  - name: "Malo - Bébé, Enfant, Parent"
    app_category: "Medical"
    web_url: "https://bonjourmalo.fr"
    android_url: "https://play.google.com/store/apps/details?id=com.kelindi.malo"
    ios_url: "https://apps.apple.com/fr/app/malo-b%C3%A9b%C3%A9-enfant-parent/id1535908879"
    image: "malo.webp"

  - name: "Virtualtrails"
    app_category: "Health & Fitness"
    web_url: "https://virtualtrails.app"
    ios_url: "https://apps.apple.com/us/app/virtualtrails/id6448714026"
    image: "virtualtrails.webp"

  - name: "Buzzsprout"
    app_category: "Podcasting"
    web_url: "https://buzzsprout.com"
    ios_url: "https://apps.apple.com/app/buzzsprout/id6459145367"
    image: "buzzsprout.webp"

  - name: "SporticalApp"
    app_category: "Sports & Entertainment"
    web_url: "https://www.sportical.app"
    ios_url: "https://apps.apple.com/app/sporticalapp/id6479256969"
    image: "sporticalapp.webp"

  - name: "OneTribe"
    app_category: "Business"
    web_url: "https://onetribe.team"
    ios_url: "https://apps.apple.com/us/app/onetribe/id6470613776"
    image: "onetribe.webp"

  - name: "Poll Everywhere"
    app_category: "Business"
    web_url: "https://polleverywhere.com"
    android_url: "https://play.google.com/store/apps/details?id=com.polleverywhere.mobile"
    ios_url: "https://apps.apple.com/us/app/poll-everywhere/id893375312"
    image: "polleverywhere.webp"

  - name: "Move"
    app_category: "Networking & Events"
    web_url: "https://m0ve.app"
    ios_url: "https://apps.apple.com/us/app/move-events/id1663690349"
    image: "move.webp"

  - name: "Uppercase"
    app_category: "Education"
    web_url: "https://www.uppercaseteach.com"
    ios_url: "https://apps.apple.com/us/app/uppercase-advice-for-teachers/id6471621007"
    image: "uppercase.webp"

  - name: "SleepHQ"
    app_category: "Health & Fitness"
    web_url: "https://sleephq.com"
    ios_url: "https://apps.apple.com/au/app/sleephq/id6451459781"
    image: "sleephq.webp"

  - name: "Baheth"
    app_category: "Education"
    web_url: "https://baheth.ieasybooks.com/"
    android_url: "https://play.google.com/store/apps/details?id=com.ieasybooks.baheth"
    ios_url: "https://apps.apple.com/us/app/باحث/id6451044688"
    image: "baheth.webp"

  - name: "BlackCandy"
    app_category: "Music"
    ios_url: "https://apps.apple.com/app/blackcandy/id6444304071"
    android_url: "https://f-droid.org/packages/org.blackcandy.android/"
    source_url: "https://github.com/blackcandy-org/blackcandy"
    image: "blackcandy.webp"

  - name: "Oxocare"
    app_category: "Health & Fitness"
    web_url: "https://oxocare.ch/"
    ios_url: "https://apps.apple.com/app/oxocare/id1444320330"
    android_url: "https://play.google.com/store/apps/details?id=ch.oxon.oxocare_mobile"
    image: "oxocare.webp"

  - name: "Musa"
    app_category: "Health & Fitness"
    web_url: "https://musa.app/"
    ios_url: "https://apps.apple.com/app/musa-cycle-syncing-dragon/id6504586102"
    image: "musa.webp"

  - name: "Friends Weekly"
    app_category: "Social Networking"
    web_url: "https://friendsweekly.com"
    ios_url: "https://apps.apple.com/us/app/friends-weekly/id6742522810"
    image: "friendsweekly.webp"

  - name: "RubyEvents"
    app_category: "Education"
    web_url: "https://www.rubyevents.org"
    ios_url: "https://apps.apple.com/app/rubyevents/id6743987375"
    image: "rubyevents.webp"

  - name: "Film Chase"
    app_category: "Entertainment"
    web_url: "https://www.filmchase.com/"
    ios_url: "https://apps.apple.com/gb/app/film-chase/id6745129572"
    image: "filmchase.webp"

  - name: "Sweeps Jobs"
    app_category: "Lifestyle"
    web_url: "https://sweeps.jobs"
    ios_url: "https://apps.apple.com/us/app/sweeps-jobs/id1617286561"
    android_url: "https://play.google.com/store/apps/details?id=com.sweepsjobs.android"
    image: "sweeps.webp"
 
  - name: "ShastaBiz"
    app_category: "Reference"
    web_url: "https://shastabiz.com"
    ios_url: "https://apps.apple.com/us/app/shastabiz/id6740650574"
    android_url: "https://play.google.com/store/apps/details?id=com.eduardosouza.shastabiz&pcampaignid=web_share" 
    image: "shastabiz.webp"

  - name: "BraveCo"
    app_category: "Lifestyle"
    web_url: "https://braveco.org"
    ios_url: "https://apps.apple.com/us/app/braveco/id6744705646"
    android_url: "https://play.google.com/store/apps/details?id=com.eduardosouza.braveco&pcampaignid=web_share" 
    image: "braveco.webp"
 
  - name: "On My Way"
    app_category: "Education"
    web_url: "https://omw.nl"
    ios_url: "https://apps.apple.com/nl/app/on-my-way/id6670307079"
    android_url: "https://play.google.com/store/apps/details?id=nl.plango.omw"
    image: "onmyway.webp"

  - name: "Ruby Friends"
    app_category: "Social Networking"
    web_url: "https://rubyfriends.app"
    ios_url: "https://apps.apple.com/us/app/ruby-friends/id6748887042"
    android_url: "https://play.google.com/store/apps/details?id=com.masilotti.rubyfriends"
    image: "rubyfriends.webp"

  - name: "Knoc Neighborhood Security"
    app_category: "Social Networking"
    web_url: "https://knoc.us"
    ios_url: "https://apps.apple.com/us/app/knoc-neighborhood-security/id6745712336"
    android_url: "https://play.google.com/store/apps/details?id=us.knoc.knoc"
    image: "knoc.webp"

  - name: "Daily Rosary App"
    app_category: "Lifestyle"
    web_url: "https://dailyrosary.app"
    ios_url: "https://apps.apple.com/us/app/daily-rosary-app/id6748244019"
    android_url: "https://play.google.com/store/apps/details?id=com.dailyrosary.app"
    image: "dailyrosaryapp.webp"

  - name: "Calendar Vision"
    app_category: "Calendar"
    web_url: "https://calendarvision.app/"
    ios_url: "https://apps.apple.com/us/app/calendar-vision/id6746702391"
    android_url: "https://play.google.com/store/apps/details?id=com.rowhomelabs.calendarvision"
    image: "calendarvision.webp"

  - name: "Ruby News"
    app_category: "News"
    web_url: "https://newsfusion.com"
    android_url: "https://play.google.com/store/apps/details?id=com.briox.riversip.programming.ruby"
    image: "rubynews.webp"

  - name: "Superconductor"
    app_category: "Developer Tools"
    ios_url: "https://apps.apple.com/us/app/superconductor/id6749349238"
    web_url: "https://www.superconductor.dev"
    image: "superconductor.webp"

  - name: "Pray-AI"
    app_category: "Lifestyle"
    web_url: "https://pray-ai.com"
    ios_url: "https://apps.apple.com/us/app/pray-ai/id6448802131"
    android_url: "https://play.google.com/store/apps/details?id=com.prayai.prayai"
    image: "prayai.webp"

  - name: "Basketball Training"
    app_category: "Sports"
    web_url: "https://www.loyal.app/"
    ios_url: "https://apps.apple.com/us/app/basketball-training-workouts/id738165126"
    android_url: "https://play.google.com/store/apps/details?id=com.fitivity.basketball_drills&hl=en_US"
    image: "basketball_training.webp"

  - name: "Cometeer"
    app_category: "Shopping"
    web_url: "https://cometeer.com"
    ios_url: "https://apps.apple.com/us/app/cometeer/id6738394746"
    image: "cometeer.webp"
